export const productos = [
    {
        id:1,
        nombre: "Remera",
        precio: 100,
        categoria: "indumentaria",
        stock: 25,
        descripcion: "La mejor remera",
        img: "",
    },
    {
        id: 2,
        nombre: "Pantalón",
        precio: 200,
        categoria: "indumentaria",
        stock: 15,
        descripcion: "Cómodo y versátil",
        img: "",
    },
    {
        id: 3,
        nombre: "Camisa",
        precio: 150,
        categoria: "indumentaria",
        stock: 30,
        descripcion: "Ideal para ocasiones formales",
        img: "",
    },
    {
        id: 4,
        nombre: "Sandalias",
        precio: 150,
        categoria: "calzado",
        stock: 10,
        descripcion: "Perfecta para días calidos",
        img: "",
    },
    {
        id: 5,
        nombre: "Zapatos",
        precio: 250,
        categoria: "calzado",
        stock: 20,
        descripcion: "Estilo y confort asegurados",
        img: "",
    },
    
];